{% set name = "interpret" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/interpretml/interpret/archive/db1a6f47b9bac288a7df80b2e489c327ce895751.tar.gz
  sha256: a083d22c879aca720fbaae077a65294d292b4bbf2977effac66cd947ee3e25ca

build:
  number: 0
  skip: true  # [linux and (s390x or aarch64 or ppc64le)]

outputs:
  - name: libebm
    script: build-libebm.sh  # [unix]
    script: bld-libebm.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('libebm', max_pin='x.x.x') }}
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - make  # [unix]
        - m2-make  # [win]
    test:
      commands:
        - if not exist %LIBRARY_BIN%\\libebm.dll exit 1  # [win]
        # IF NOT EXIST "%LIBRARY_BIN%\libebm.dll" EXIT /B 1  # [win]
        - test -f $PREFIX/lib/libebm.so       # [linux]
        - test -f $PREFIX/lib/libebm.dylib     # [osx]

  - name: {{ name }}-core
    script: build_interpret-core.sh  # [unix]
    script: bld_interpret-core.bat  # [win]
    build: 
      missing_dso_whitelist:  # [linux]
        - /lib64/libm.so.6    # [linux]
    requirements:
      build:
        - nodejs ==16.*
      host:
        - setuptools
        - wheel
        - pip
        - python
      run:
        - python
        - numpy >=1.11.1
        - scipy >=0.18.1
        - pandas >=0.19.2
        - scikit-learn >=0.18.1
        - joblib >=0.11
        - libebm  =={{ version }}
    test:
      imports:
        - interpret

  - name: {{ name }}
    script: build_interpret.sh  # [unix]
    script: bld_interpret.bat  # [win]
    requirements:
      host:
        - python
        - wheel
        - pip
        - setuptools
      run:
        - python
        - interpret-core =={{ version }}
        # Equiv. to extras.
        - psutil >=5.6.2 
        - ipykernel >=4.10.0
        - ipython >=5.5.0
        - plotly >=3.8.1
        - lime >=0.1.1.33
        - SALib >=1.3.3
        - shap >=0.28.5
        - dill >=0.2.5
        # - skope-rules >=1.0.1    fails on python 3.10
        - treeinterpreter >=0.2.2
        - dash >=2.0.0 # dash 2.* removed the dependencies on: dash-html-components, dash-core-components, dash-table
        - dash_cytoscape >=0.1.1
        - gevent >=1.3.6
        - requests >=2.19.0

    test:
      source_files:
        - python/interpret-core/tests
      requires:
        - pytest
        - pytest-runner >=4.4
        - pytest-xdist >=1.29
        - nbconvert >=5.4.1
        - selenium >=3.141.0
        - pytest-cov >=2.6.1
        - flake8 >=3.7.7
        - jupyter >=1.0.0
        - ipywidgets >=7.4.2
      imports:
        - interpret
      commands:
        - python -m pytest python/interpret-core/tests -vv -k "not test_ebm_predict_and_contrib_logits"

about:
  home: https://github.com/interpretml/interpret
  summary: Fit interpretable models. Explain blackbox machine learning.
  description: |
    In the beginning machines learned in darkness, and data scientists struggled in the void to explain them.
    Let there be light.
    https://github.com/interpretml/interpret
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://interpret.ml/docs/getting-started
  dev_url: https://interpret.ml/docs/installation-guide.html

extra:
  recipe-maintainers:
    - paulbkoch
    - interpret-ml
